In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd 
data = pd.read_csv('/content/drive/MyDrive/Thesis/Data/Filled Datasets/Second dataset (Kaggle)/Preprocessed/combined_train_val.csv',header=0)
test = pd.read_csv('/content/drive/MyDrive/Thesis/Data/Filled Datasets/Second dataset (Kaggle)/Preprocessed/Constraint_Test_fullprep_with_labels.csv')

In [3]:
test

id                                              tweet  label
0        1  daily update published states reported k tests...      0
1        2                                 alfalfa cure covid      1
2        3      president trump asked would catch coronavirus      1
3        4  states reported deaths still seeing solid nati...      0
4        5  sixth time global health emergency declared in...      0
...    ...                                                ...    ...
2134  2136  state wise details total confirmed cases till ...      0
2135  2137  tonight midnight onwards disaster management a...      1
2136  2138  new cases plateau enough yo lagos rivers ft fa...      0
2137  2139  one stop shop resources section communicating ...      0
2138  2140  half pregnant women recently admitted uk hospi...      0

[2139 rows x 3 columns]

In [4]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sn
import pickle

%matplotlib inline

#Import module to split the datasets
from sklearn.model_selection import train_test_split
# Import modules to evaluate the metrics
from sklearn import metrics
from sklearn.metrics import confusion_matrix,accuracy_score,roc_auc_score,roc_curve,auc

In [5]:
y_train = data["label"]
X_train = data["tweet"]
y_test = test["label"]
X_test = test["tweet"]

For evaluation metrics: 

In [6]:
# Create the confussion matrix
def plot_confussion_matrix(y_test, y_pred):
    ''' Plot the confussion matrix for the target labels and predictions '''
    cm = confusion_matrix(y_test, y_pred)

    # Create a dataframe with the confussion matrix values
    df_cm = pd.DataFrame(cm, range(cm.shape[0]),
                  range(cm.shape[1]))
    #plt.figure(figsize = (10,7))
    # Plot the confussion matrix
    sn.set(font_scale=1.4) #for label size
    sn.heatmap(df_cm, annot=True,fmt='.0f',annot_kws={"size": 10})# font size
    plt.show()
    
# ROC Curve
# plot no skill
# Calculate the points in the ROC curve
def plot_roc_curve(y_test, y_pred):
    ''' Plot the ROC curve for the target labels and predictions'''
    fpr, tpr, thresholds = roc_curve(y_test, y_pred, pos_label=1)
    roc_auc= auc(fpr,tpr)

    plt.title('Receiver Operating Characteristic')
    plt.plot(fpr, tpr, 'b', label = 'AUC = %0.2f' % roc_auc)
    plt.legend(loc = 'lower right')
    plt.plot([0, 1], [0, 1],'r--')
    plt.xlim([0, 1])
    plt.ylim([0, 1])
    plt.ylabel('True Positive Rate')
    plt.xlabel('False Positive Rate')
    plt.show()

In [8]:
from imblearn.over_sampling import SMOTE

**THE SVM MODEL:**



With TF unigram:

In [12]:
from sklearn.svm import SVC
SVM_tf = SVC()

from sklearn.feature_extraction.text import CountVectorizer

tf = CountVectorizer()

X_train_tf = tf.fit_transform(X_train)
X_test_tf = tf.transform(X_test)

smote = SMOTE()
X_train_tf, y_train_tf = smote.fit_resample(X_train_tf,y_train)

SVM_tf.fit(X_train_tf, y_train_tf)

y_pred = SVM_tf.predict(X_test_tf)

print(metrics.classification_report(y_test, y_pred,  digits=5))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0    0.93814   0.89455   0.91583      1119
           1    0.88993   0.93529   0.91205      1020

    accuracy                        0.91398      2139
   macro avg    0.91403   0.91492   0.91394      2139
weighted avg    0.91515   0.91398   0.91402      2139

[[1001  118]
 [  66  954]]


With TF bigram:

In [ ]:
from sklearn.svm import SVC
SVM_tf_bi = SVC()

from sklearn.feature_extraction.text import CountVectorizer

tf_bi = CountVectorizer(ngram_range = (2,2))

X_train_tf_bi = tf_bi.fit_transform(X_train)
X_test_tf_bi = tf_bi.transform(X_test)

smote = SMOTE()
X_train_tf_bi, y_train_tf_bi = smote.fit_resample(X_train_tf_bi,y_train)

SVM_tf_bi.fit(X_train_tf_bi, y_train_tf_bi)

y_pred = SVM_tf_bi.predict(X_test_tf_bi)

print(metrics.classification_report(y_test, y_pred,  digits=5))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0    0.98292   0.56568   0.71809      1119
           1    0.67492   0.98922   0.80239      1020

    accuracy                        0.76765      2139
   macro avg    0.82892   0.77745   0.76024      2139
weighted avg    0.83605   0.76765   0.75829      2139

[[ 633  486]
 [  11 1009]]


With TFIDF unigram:

In [ ]:
from sklearn.svm import SVC
SVM_tfidf = SVC()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

smote = SMOTE()
X_train_tfidf, y_train_tfidf = smote.fit_resample(X_train_tfidf,y_train)

SVM_tfidf.fit(X_train_tfidf, y_train_tfidf)

y_pred = SVM_tfidf.predict(X_test_tfidf)

print(metrics.classification_report(y_test, y_pred,  digits=5))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0    0.94800   0.91242   0.92987      1119
           1    0.90772   0.94510   0.92603      1020

    accuracy                        0.92800      2139
   macro avg    0.92786   0.92876   0.92795      2139
weighted avg    0.92879   0.92800   0.92804      2139

[[1021   98]
 [  56  964]]


With TFIDF bigram:

In [ ]:
from sklearn.svm import SVC
SVM_tfidf_bi = SVC()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_bi = TfidfVectorizer(ngram_range = (2,2))

X_train_tfidf_bi = tfidf_bi.fit_transform(X_train)
X_test_tfidf_bi = tfidf_bi.transform(X_test)

smote = SMOTE()
X_train_tfidf_bi, y_train_tfidf_bi = smote.fit_resample(X_train_tfidf_bi,y_train)

SVM_tfidf_bi.fit(X_train_tfidf_bi, y_train_tfidf_bi)

y_pred = SVM_tfidf_bi.predict(X_test_tfidf_bi)

print(metrics.classification_report(y_test, y_pred,  digits=5))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0    0.94559   0.82306   0.88008      1119
           1    0.83004   0.94804   0.88513      1020

    accuracy                        0.88266      2139
   macro avg    0.88781   0.88555   0.88260      2139
weighted avg    0.89049   0.88266   0.88248      2139

[[921 198]
 [ 53 967]]


**Now we try gridsearch on the optimal model = TFIDF unigram**

Base model:

In [13]:
from sklearn.svm import SVC
SVM_tfidf = SVC()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

smote = SMOTE()
X_train_tfidf, y_train_tfidf = smote.fit_resample(X_train_tfidf,y_train)

SVM_tfidf.fit(X_train_tfidf, y_train_tfidf)

y_pred = SVM_tfidf.predict(X_test_tfidf)

print(metrics.classification_report(y_test, y_pred,  digits=5))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0    0.94537   0.91242   0.92860      1119
           1    0.90746   0.94216   0.92448      1020

    accuracy                        0.92660      2139
   macro avg    0.92642   0.92729   0.92654      2139
weighted avg    0.92729   0.92660   0.92664      2139

[[1021   98]
 [  59  961]]


Grid search:

grid = {
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001]
    }

In [ ]:
#this works, and output is written to file
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

import sys
import logging
import uuid
os.chdir("/content/drive/MyDrive/Thesis/Models/Replicated models/Simple models/SVM/")
so = open("data.log - SVM TFIDF GRID" +str(uuid.uuid4()), 'w', 10)
sys.stdout.echo = so
sys.stderr.echo = so

get_ipython().log.handlers[0].stream = so
get_ipython().log.setLevel(logging.INFO)

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

parameters = {
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001]
    }

SVM = GridSearchCV(SVC(kernel='rbf'), parameters, cv=3, n_jobs=-1,verbose = 2).fit(X_train_tfidf, y_train_tfidf)
print("train score:", SVM.score(X_train_tfidf, y_train_tfidf))
print("test score:", SVM.score(X_test_tfidf, y_test))
print(" Results from Grid Search" )
print("\n The best estimator across ALL searched params:\n",SVM.best_estimator_)
print("\n The best score across ALL searched params:\n",SVM.best_score_)
print("\n The best parameters across ALL searched params:\n",SVM.best_params_)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
train score: 1.0
test score: 0.9308087891538102
 Results from Grid Search

 The best estimator across ALL searched params:
 SVC(C=10, gamma=1)

 The best score across ALL searched params:
 0.9308036319922612

 The best parameters across ALL searched params:
 {'C': 10, 'gamma': 1}


In [15]:
from sklearn import svm

SVM_optimal = svm.SVC(C=10, gamma = 1)

In [16]:
SVM_optimal.fit(X_train_tfidf, y_train_tfidf)

SVC(C=10, gamma=1)

In [18]:
y_pred = SVM_optimal.predict(X_test_tfidf)

print(metrics.classification_report(y_test, y_pred,  digits=2))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.93      0.93      1119
           1       0.92      0.94      0.93      1020

    accuracy                           0.93      2139
   macro avg       0.93      0.93      0.93      2139
weighted avg       0.93      0.93      0.93      2139

[[1036   83]
 [  65  955]]


**Now we'll do the grid search again with TFIDF bigrams**

In [19]:
tfidf_bi=TfidfVectorizer(ngram_range=(2,2))

# transform and fit the training set with vectoriser
X_train_tfidf_bi = tfidf_bi.fit_transform(X_train)
# transform the test set with vectoriser
X_test_tfidf_bi = tfidf_bi.transform(X_test)

smote = SMOTE()
X_train_tfidf_bi, y_train_tfidf_bi = smote.fit_resample(X_train_tfidf_bi,y_train)

In [ ]:
#this works, and output is written to file
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

import sys
import logging
import uuid
os.chdir("/content/drive/MyDrive/Thesis/Models/Replicated models/Simple models/SVM/")
so = open("data.log - SVM TFIDF BIGRAM GRID" +str(uuid.uuid4()), 'w', 10)
sys.stdout.echo = so
sys.stderr.echo = so

get_ipython().log.handlers[0].stream = so
get_ipython().log.setLevel(logging.INFO)

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

parameters = {
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001]
    }

SVM = GridSearchCV(SVC(kernel='rbf'), parameters, cv=3, n_jobs=-1,verbose = 2).fit(X_train_tfidf_bi, y_train_tfidf_bi)
print("train score:", SVM.score(X_train_tfidf_bi, y_train_tfidf_bi))
print("test score:", SVM.score(X_test_tfidf_bi, y_test))
print(" Results from Grid Search" )
print("\n The best estimator across ALL searched params:\n",SVM.best_estimator_)
print("\n The best score across ALL searched params:\n",SVM.best_score_)
print("\n The best parameters across ALL searched params:\n",SVM.best_params_)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
train score: 0.9997767857142857
test score: 0.8966806919121084
 Results from Grid Search

 The best estimator across ALL searched params:
 SVC(C=100, gamma=0.1)

 The best score across ALL searched params:
 0.8774554288349163

 The best parameters across ALL searched params:
 {'C': 100, 'gamma': 0.1}


In [20]:
from sklearn import svm

SVM_optimal_bi = svm.SVC(C=100, gamma = 0.1)

In [21]:
SVM_optimal_bi.fit(X_train_tfidf_bi, y_train_tfidf_bi)

SVC(C=100, gamma=0.1)

In [22]:
y_pred = SVM_optimal_bi.predict(X_test_tfidf_bi)

print(metrics.classification_report(y_test, y_pred,  digits=2))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.88      0.90      1119
           1       0.87      0.92      0.89      1020

    accuracy                           0.90      2139
   macro avg       0.90      0.90      0.90      2139
weighted avg       0.90      0.90      0.90      2139

[[981 138]
 [ 83 937]]
